basic:
    name: 'https://rnid.org.uk'
    environments:
        production: 'https://rnid.org.uk'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 760
        - 768
        - 1024
        - 1080
        - 1200
        - 1920
    pages:
        - /
        - /get-involved/donate
        - /information-and-support
        - /information-and-support/ear-health
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: ''
    retina_images: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
